### ISSUE TITLE
support for python3

### ISSUE THREAD

**Issue by Trophime** [hpddm/hpddm#16]
Hi Pierre,
could you add support for python3?
python2 will be unavailable on future Debian/Ubuntu release...

Best
C

PS: for freefem++ which version of hpddm shall I use?

**Comment by prj-** [comment]
Dear Christophe,
Python3 should be supported, at least version 3.7 (and 2.7) is used on Travis, cf. the build [matrix](https://travis-ci.org/hpddm/hpddm). If you want to use HPDDM inside FreeFEM, I'd recommend compiling PETSc with the flag `--download-hpddm`, cf. this [slide](http://jolivet.perso.enseeiht.fr/FreeFem-tutorial/main.html#pfc2) and the next one. If you don't compile PETSc yourself (or don't want PETSc with FreeFEM), the HEAD of `master` from this repository is alright with FreeFEM. Let me know if you encounter any issue.

**Comment by Trophime** [comment]
Can I compile hpddm support in petsc with something like:
```
 --with-hpddm=1 --with-hpddm-include=/usr/include/hpddm \
 --with-hpddm-lib=/usr/lib/$(DEB_HOST_GNU_TYPE)/libhpddm_c.so
```

**Comment by Trophime** [comment]
unless I'm wrong it does not seem to work :(

**Comment by Trophime** [comment]
I've found part of the trouble. HPDDM is supported in petsc 3.12 and above only...
I was trying with petsc 3.11 ...

**Comment by prj-** [comment]
Furthermore:
* it's not possible to use `--with-hpddm` since `skippackagewithoptions` is set to 1, cf. [hpddm.py](https://gitlab.com/petsc/petsc/blob/c5910190/config/BuildSystem/config/packages/hpddm.py#L16). Only `--download-hpddm` is possible (this could be fixed but this is not trivial since HPDDM may or may not use SLEPc, so there is some tinkering to do with PETSc BuildSystem)
* HPDDM is header-only, `libhpddm_c.so` is needed if you want to use it from C, outside of FreeFEM or PETSc

I'll try to make it possible to externalize the compilation of [hpddm_petsc.cpp](https://github.com/hpddm/hpddm/blob/master/interface/hpddm_petsc.cpp), so that one can compile PETSc, then compile SLEPc, and then compile the HPDDM interface (so that we don't rely on people configuring PETSc with `--download-slepc --download-hpddm`).

**Comment by Trophime** [comment]
And I cannot used PETSC/SLEPC in freefem without HPDDM right?
So far there is no better way than the one you suggested in your first comment, I guess

**Comment by prj-** [comment]
> And I cannot used PETSC/SLEPC in freefem without HPDDM right?

Right.

> So far there is no better way than the one you suggested in your first comment, I guess

It should be the easiest, indeed. That's what we do now in [FreeFEM](https://github.com/FreeFem/FreeFem-sources/blob/361cd8933952c1a4031bf3cb89de25936073acae/3rdparty/ff-petsc/Makefile#L51-L54). If this doesn't work, please let us know.

**Comment by prj-** [comment]
We have recently added the `--download-hpddm` option to [SLEPc](https://gitlab.com/slepc/slepc/commit/539ab03de10be0b3294038b0d61e4aa011d970e0) as well. So, that means that if you don't want to `./configure` PETSc with `--download-hpddm --download-slepc`, you can keep your library as it is right now. You'll need to reconfigure SLEPc with the new flag though. I can also help you compile the interface from outside of SLEPc as well, but you'll loose the benefits of having `KSPHPDDM` and `PCHPDDM` automatically registered for you. If the current compilation process is acceptable to you, please close the issue. Thanks.
